### ISSUE TITLE
angular 4 not supported

### ISSUE THREAD

**Issue by danish-monu** [rangle/augury#1063]
is angular 4 not supported?

**Comment by raydaim** [comment]
@danish-monu  Yeah I am using augury with angular 4.0.1

**Comment by danish-monu** [comment]
really. for me, it popped out an error message saying not an angular project.

**Comment by thaoula** [comment]
i also get message saying my app is not an angular app. I am using Angular 4.0.1

I also get these errors which disappear when i disable Augury -

zone.js:569 Unhandled Promise rejection: Cannot read property 'injector' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'injector' of null

zone.js:571 Error: Uncaught (in promise): TypeError: Cannot read property 'injector' of null
TypeError: Cannot read property 'injector' of null

Regards,
Tarek

**Comment by itsnotvalid** [comment]
I think it definitely not supporting angular 4. Just to see how we could help to make it support.

**Comment by stevenkampen** [comment]
@danish-monu It sounds like you hit the issue in the late RC stages (`window.ng` was not present in debug mode) which was later fixed by angular.

@thaoula It sounds like you hit an error that happened just after 4.0.0 release because of a change in an unofficial API within the router. It was fixed by us soon after so you shouldn't see the issue now.

Anyone else, if you're seeing issues, please report them, but I don't believe there are any. Closing this issue.

**Comment by thaoula** [comment]
Hi Steven,

Thanks for your reply.

The issue i initially reported seem to have been resolved. However, i now get the following on AOT project build with Angular CLI

![image](https://cloud.githubusercontent.com/assets/349133/25131901/ddc9f05c-248a-11e7-9e09-6a177343f7f1.png)

**Comment by stevenkampen** [comment]
@thaoula Thanks for the report. I've added an issue for it here: #1070.
