### ISSUE TITLE
EntryComponents are not visible in augury

### ISSUE THREAD

**Issue by Mohendran** [rangle/augury#1214]
Augury version (required): 1.14.0
Angular version (required): 4.0.3

Steps to reproduce:

1. Use ng-bootstrap (Modal)
2. Include ur template in the entryComponents field in ur module
3. Open Augury... U will not be able to see the component for debugging

**Comment by will093** [comment]
I am having the same problem.

**Comment by arafeek** [comment]
Hi @Mohendran would you be able to elaborate on your project structure a little? Also, if you could add a snippet of how you are importing the modal component / its template that would be helpful. Thanks.

**Comment by Mohendran** [comment]
@arafeek 
Iam following the same snippet as in ng-bootstrap

http://plnkr.co/edit/HebLTX5kLrWK7qif3wp3?p=preview

**Comment by arafeek** [comment]
@Mohendran Sorry for the late reply. This issue seems to be due to the fact that these dynamically loaded components do not show up in calls to `ng.probe()`. Unfortunately at this time Augury makes heavy use of `ng.probe()` to gather information about the running application and so is unaware of their presence. Currently investigating how we can get around this limitation.

**Comment by Mohendran** [comment]
@arafeek 👍  Augury is awesome... u guys are making it extra awesome

**Comment by mariannafld** [comment]
@arafeek, Did you found the way how to allow  to debug dynamically loaded components (modal dialogs)? Thank you in advance, 👍

**Comment by mladen7** [comment]
This would obviously be a great feature and i see requests for this going back to the previous year, dunno why it is not resolved yet... still not working

**Comment by andrewthauer** [comment]
Created consolidated issue #1380 to track this
