### ISSUE TITLE
State does not show up if your component uses a service with a function called 'delete'

### ISSUE THREAD

**Issue by Devcon4** [rangle/augury#1234]
Augury version (1.14.0):
Angular version (4.3.6):
Date: 8/23/2017
OS: Windows 10

Demo test application:
[Github repo](https://github.com/Devcon4/StateIssue)

Description of issue:
We generate a DataService that mirrors our backend, In doing so we end up with a service with objects with functions that match our controllers. Sometimes we have a api call called 'delete'. I noticed that several of our components don't have the state section visible in Augury. After hunting down the issues I figured out that if comes from our DataService because of the delete function. Renaming them to anything else fixes the issue. In the repo there is a service with an object with a function called delete, if you comment it out then the state of AppComponent will show up again.

Steps to reproduce:
1. Create a new project (Or clone the repo).
2. Create a service and add an object with a function called 'delete'
`projects = {
    read: () => null,
    delete: () => null
}`
3. In a component inject this service.
4. Inspect that component in Augury and the state section does not show up.

Additional details:
I don't know what should be done about this, I do find having functions called delete to be wrong, but I think it should at least be a known issue.
I'm also not sure if the delete function has to be in an object, that is just how our use case got the bug.

**Comment by arafeek** [comment]
Hey @Devcon4 thanks for your feedback. 

The issue you are experiencing is related to the way we pass messages about component state Augury. In order to correctly handle complex objects properly, our serialization process creates a function representation of the object capable of properly reconstructing itself when called. You can see how this works in ![serialize.ts](https://github.com/rangle/augury/blob/dev/src/utils/serialize.ts#L3-L88) .  


The specific issue you are experiencing is due to how the `projects` object gets represented by the serializer. Here is a snippet of a similar object I serialized:  
![snip20170824_9](https://user-images.githubusercontent.com/7095609/29672712-0620458a-88bb-11e7-9cb1-ce68bbabb215.png)

As you can see, it attempts to make a function called `delete()` which when executed during deserialization causes it to fail, leading to no state for that component being rendered.

I think we could improve how this is handled (maybe throw an error or some indication that it failed) in the interim.

For now, I think listing this as a known issue would serve the community best until the augury team comes up with a proper fix.

**Comment by arafeek** [comment]
Tracked ![here](https://github.com/rangle/augury/pull/1235)
