### ISSUE TITLE
[feature request] Component Tree snapshot and diff

### ISSUE THREAD

**Issue by walrus95** [rangle/augury#1305]
Augury version (required): 1.16.1 (canary on Chrome)
Angular version (required): 4.4.3
Date: 5/16/18
OS: Windows 10

Description of issue:
I often find myself digging through the Component Tree in Augury trying to figure out what has changed in the properties of various components in the Component Tree after having performed some action in my application.

I would like to see a “snapshot” feature added to the Component Tree in Augury which would allow the user to capture the state of the component tree at a given point in time. The user would be able to take a snapshot, perform some actions, and then take a second snapshot. Both snapshots would be saved to a list of snapshots in Augury.

I would like to see an additional feature added to Augury which would allow the user to compare any two Component Tree snapshots to show their differences not only at the component level but at the property level as well. This feature could be called “diff.”

It would be nice to be able to save and load snapshots to and from disk. You could take inspiration from the "Memory" tab in Chrome devtools, as it can do snapshots.

Thank you!

**Comment by santiago-elustondo** [comment]
Hey, @walrus95 

Thanks for the suggestion. That does sound useful. I can imagine a possible interface similar to Redux DevTools, where you see snapshots and their diffs for the component tree, instead of the redux store.

This would not be a simple feature to add given the current architecture, but we are planning to perhaps undergo some architectural work in the very near future. 

We'll keep this feature in mind as we plan ahead.

**Comment by andrewthauer** [comment]
@walrus95 - You may want to checkout https://github.com/rangle/augury-labs. This covers this use case. Please refer there. Feedback is very much appreciated and welcome.
