### ISSUE TITLE
Add Augury icon in address and open tools on clicking

### ISSUE THREAD

**Issue by sumitarora** [rangle/augury#157]

**Comment by mobinni** [comment]
Hi, I was implementing this feature and actually had a question: does this have to show on every page or just the pages that actually have angular 2 loaded. I ask because the content_script cannot access the JS variables created on the actual page. It runs sandboxed:  
https://developer.chrome.com/extensions/content_scripts  
http://stackoverflow.com/questions/18707341/how-to-access-page-variables-from-chrome-extension-background-script  
  
This iwhat it currently looks like (but this shows on every page):  
![screen shot 2016-03-01 at 23 32 00](https://cloud.githubusercontent.com/assets/2361292/13444326/dd352294-e005-11e5-962e-1113607f59f9.png)

**Comment by sumitarora** [comment]
@mobinni It should only show on the pages which are created using angular2 you can access page data by message pa

**Comment by vanessayuenn** [comment]
hey @mobinni, responded to you on slack but reposting my response here for reference: this issue is actually deferred for the moment because opening devtools in chrome programmatically is not currently allowed (see https://bugs.chromium.org/p/chromium/issues/detail?id=112277). we're working to get permission for that.

**Comment by xorgy** [comment]
We can't open the DevTools programmatically because there is no API for this.
