### ISSUE TITLE
Show Augury icon in title bar

### ISSUE THREAD

**Issue by mobinni** [rangle/augury#249]
Complementary to the fix proposed by @vanessayuenn for issue #238 I think it would be nice to add the batarangle icon to the title bar, to signify the site is running Angular 2.0.

This was proposed in issue #157 with the possibility of opening the dev tools immediately. However, I think you can implement it without that specific feature for now, and it would still be very useful.

This would give developers not only a good indication that their Angular is loaded correctly, but also to see what other sites are running angular 2 at a glance.

![](https://cloud.githubusercontent.com/assets/2361292/13444326/dd352294-e005-11e5-962e-1113607f59f9.png)

**Comment by igor-ka** [comment]
@mobinni this issue is already out of date. It seems to be partially resolved by #157. In terms of opening devtools portion, there seem to be security limitation in Chrome that do not allow us to do that.

I will be closing the issue, let me know if I am missing something and we can reopen and update this issue.
