### ISSUE TITLE
Find bottlenecks in Augury

### ISSUE THREAD

**Issue by ericjim** [rangle/augury#485]
* Backend
  * `_traverseElements`? forEach is a blocking and `this._traverseElements` is being called recursively.
   * Can I perform ` _traverseElements` async or off-load the computation to a web worker.
* Frontend
  * `component-tree.ts` would using change detection and immutable data improve things?

**Comment by sumitarora** [comment]
@ericjim It's `_traverseElements` now

**Comment by ericjim** [comment]
My preliminary findings.

The component tree (`component-tree.ts`) is comprised of a recursive component that eagerly evaluates all of its children (`bt-node-item`). We can account for major slowdowns whenever a large influx of nodes are added to our tree. 

Furthermore, the default behaviour of the upside down arrow cursor (or disclosure arrow) is to reveal the immediate child. This behaviour trickles down the component tree, thereby showing the entirety of the tree.

My suggestion to alleviate loading issues, for lack of a better term, would be to “lazily render” the child nodes of any component until it is needed. 

We can specify “Need” as:
* Being the node focused by the user.
* Being the next immediate node that the user will actuate on, but not that child’s child.

The downside to this behaviour, however, is the need to dig down the component tree to display all elements.

**Comment by sumitarora** [comment]
@ericjim One other thing, we have to think about is how would search behave in this aspect? We would have all the data and search can be performed on those. We open the hierarchy of the component being searched and close other??

**Comment by sumitarora** [comment]
@ericjim One other thing, we have to think about is how would search behave in this aspect? We would have all the data and search can be performed on those. We open the hierarchy of the component being searched and close other??

**Comment by sumitarora** [comment]
@ericjim One other thing, we have to think about is how would search behave in this aspect? We would have all the data and the search can be performed on it. Do we open the hierarchy of the component being searched and close other?

**Comment by igor-ka** [comment]
@sumitarora we discussed this with @ericjim this morning. Below are the three high level items that we are currently thinking of:

1) Don't "load" nested items unless opened. Will probably help apps that have deep component hierarchies
2) Only render the part of the tree that is currently visible, kind of like virtual scrolling
3) Optimize A2's rendering cycle by leveraging change detection better, or iterable differs?

I think that a combination of those 3 things with some improvements on the UX can greatly improve the situation.

For the search, especially since this is only done by component name, we can leverage a much simpler and potentially flatter version of the tree or something. But we should keep that feature in mind.

cc'ing @clbond @yuri @e-schultz for additional thoughts.

**Comment by ericjim** [comment]
I have solutions to problems, but now I need to be able to measure things to make performance claims. I'll look into calculating metrics within the stress testing app. On that note, I should add a stress test that probes really tall/deep trees.

**Comment by clbond** [comment]
The performance problems have been resolved by the backend rewrite at https://github.com/rangle/augury/commit/dfa410b6545f24e3cef87af775b4e9651ffad13f

**Comment by ericjim** [comment]
@clbond do you feel we can close this issue now?

**Comment by clbond** [comment]
Yes. This has been addressed. Even the app that Igor uses to test performance that would hang the application for multiple minutes runs quickly now.
