### ISSUE TITLE
Problems on using Asana application

### ISSUE THREAD

**Issue by emilianosantucci** [rangle/augury#681]
Hi guys, 
I'm using [Asana](www.asana.com) as task issue platform and on weekends I found some problems on load there website.

After some investigation, the issue seems to be caused by your plugin (when I disabled it, the website start without problem).

When I try login, receive that on console:

<img width="950" alt="screen shot 2016-09-19 at 15 24 59" src="https://cloud.githubusercontent.com/assets/13835650/18634344/ce866cca-7e80-11e6-9d19-ecacf3299051.png">

Currently, I found that issue is on Asana but I'm not sure is only linked on it.

Any notice of that?

Thanks

**Comment by NoNameProvided** [comment]
Same here.

**Comment by igor-ka** [comment]
This issue is a duplicate of #734

**Comment by emilianosantucci** [comment]
@igor-ka this issue has created before #734 but it's the same :).
Do you prefer if I close it?

**Comment by igor-ka** [comment]
@emilianosantucci I marked this one as the duplicate because I encountered it second on the list. Hope that is ok :)

Otherwise, it would be great if you can test the PR against your specific use case and close the issue if it addresses it for you. The build with the PR should be available [here](https://1382-41743300-gh.circle-artifacts.com/0/tmp/circle-artifacts.6V9XqAa/augury-1382.crx)

**Comment by emilianosantucci** [comment]
@igor-ka I can't install your attachment but I have cloned `dev` project where you have merged the PR and it works fine.

Have you a prevision for production release?
