### ISSUE TITLE
New property is not shown in the property when it's add to a component.

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#821]
Augury does not correctly update the property tab view when a new property is added to a component. You need to click on a different component and back again for it to appear correctly.

This happens in the code if a property is declared but not initialized with a value, for example here the property count will get compiled away by TypeScript until it holds a value.

```
export class AppComponent {
  title = 'Angular Input Output';
  count: number;

  @Input() message = "Message Board"
```

What we see is something like this initially

<img width="247" alt="screen shot 2016-11-24 at 10 36 37 am" src="https://cloud.githubusercontent.com/assets/439226/20606220/7bdd6910-b23d-11e6-97ad-72645983456a.png">

Some time later when count holds a value it's appears in the property tab view, but the User is forced to manually refresh the view by click on a different component and then back on the AppComponent.

<img width="241" alt="screen shot 2016-11-24 at 11 41 22 am" src="https://cloud.githubusercontent.com/assets/439226/20606250/b3befe98-b23d-11e6-953c-159a9c63b2eb.png">

The ideal fix would have this property shown automatically when a (new) value is bound to it.

**Comment by mobinni** [comment]
reference to backend.ts:
```
  const ngZone = root.injector.get(ng.coreTokens.NgZone);
  if (ngZone) {
    subscriptions.push(ngZone.onStable.subscribe(() => subject.next(void 0)));
  }

  subscriptions.push(
    subject.debounceTime(0).subscribe(() => {
      updateComponentTree(getAllAngularRootElements().map(r => ng.probe(r)));
      updateRouterTree(routerTree());
    }));

  subject.next(void 0); // initial load
```

**Comment by stevenkampen** [comment]
@rajinder-yadav Just to confirm what you saw here... With typescript v2, the uninitialized class member is still compiled out (doesn't exist in the "state"), but when updated (as a result of a `setTimeout`) *does* appears automatically, without having to refresh Augury's view of the component by clicking on another component or anything like that. Is that correct?

I tested with:
```
export class AppComponent {
  title = 'Augury Routes Demo';
  private count: number;
  constructor() {
    setTimeout(() => this.count = 1, 3000);
  }
}
```

Which generated the JS:
```
    function AppComponent() {
        var _this = this;
        this.title = 'Augury Routes Demo';
        setTimeout(function () { return _this.count = 1; }, 3000);
    }
```

If we're on the same page, then the question is "Is this expected behaviour for TS? (the compiling out of uninitialized class members)."

I am not expert enough to know off hand, but I guess we should look for that answer, if you agree.

**Comment by rajinder-yadav** [comment]
This issues seem to have been fixed, I was unable to recreate is with a demo app. Also In the Guide, we have a demo app for Input Output and it use to have the same problem, which is now gone. Closing as can't reproduce.
