### ISSUE TITLE
Injector graph looks wrong

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#884]
This is not a new bug, I believe we've always showed things this way.

In the Augury demo Form app, Augury incorrectly shows "NewUserService" being injected by the AppComponent, this is really not the case.

The NewUserService belongs to the entire app, which is getting injected by the "Root injector". This is defined in App's NgModule.

<img width="513" alt="screen shot 2016-12-14 at 2 43 02 pm" src="https://cloud.githubusercontent.com/assets/439226/21198067/e0d3c084-c20b-11e6-8f53-fe29f73d455f.png">

We need another way to show this, maybe another level simply labeled the "Root Injector"? In the demo app, AppComponent does not make use of or provide the service "NewUserService".

If you look at the code both UserInfoComponent and FormNewUserComponent use DI to create NewUserService in the constructor, which is coming from the "Root injector".

Looking at the Injector graph, I start to think the NewUserService service as being provided at the app level via a meta-data property in the decorator like:

```js
@Component({
...
 providers: [NewUserService],
...
})
export class AppComponent
```

This is not the case.

**Comment by stevenkampen** [comment]
@rajinder-yadav Yes, that's because the old injector graph was showing that it was 'provided' at that level (for reasons I never quite grasped). I've included screenshots of what it looks like with the new injector graph. 
<img width="276" alt="screen shot 2016-12-15 at 10 55 13 am" src="https://cloud.githubusercontent.com/assets/898763/21219450/2624e344-c2b5-11e6-9388-29c38369b1b5.png">
<img width="277" alt="screen shot 2016-12-15 at 10 55 06 am" src="https://cloud.githubusercontent.com/assets/898763/21219451/2626fd00-c2b5-11e6-9f77-963e4d8b53b7.png">

**Comment by stevenkampen** [comment]
This is resolved now with the injector graph improvements in #867
