### ISSUE TITLE
Fix build script to fetch kitchen app from new repo

### ISSUE THREAD

**Issue by rajinder-yadav** [rangle/augury#897]
The kitchen sink app has been moved to the augury-examples repo, and it's code will be delete from augury repo.

This will require the build script to pick up the app from the new location so it continue to work when people visit: https://augury.angular.io/dem.

**Comment by mobinni** [comment]
Created a PR for a staging build: https://github.com/rangle/augury.angular.io/pull/51

Please cleanup the app folder of the kitchen-sink examples. It builds multiple output files to the app folder. Also the index.html should output the vendor scripts with a ```./vendors.[hash].js``` instead of the ```/vendors``` please fix this. It is necessary before staging can be merged into master for the augury website.
